# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weatherinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(max_length=20)),
                ('month', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=5)),
            ],
        ),
    ]
